@startuml 2d_srpg_class
title 2DSRPG クラス図

left to right direction

enum TileType {
    GRASS = 1
    THICKET = 2
    FOREST = 3
    SAND = 4
    WATER = 5
    WALL = 6

    CASTLE_LEFT_TOP = 101
    CASTLE_RIGHT_TOP = 102
    CASTLE_LEFT_BOTTOM = 103
    CASTLE_RIGHT_BUTTON = 104

    CITY_LEFT = 111
    CITY_RIGHT = 112
}

enum ItemTargetType {
    MYSELF
    UNIT
    TILE
}

enum UnitType {
    ALLY
    ENEMY
}

interface ISavaToJson {
    ..JSON形式での保存・読み込みを規定するインターフェース..
    -JsonHandler json_handler;
    +abstract SaveData(): void;
    +abstract LoadData(string json_text): void;
}

class GameManager {
    +UnitManager unit_manager;
    +MapManager map_manager;
}

class SaveDataHolderSo {
    ..セーブデータをまとめて保持するScriptableObject..
    +AllyUnitSaveData[] ally_uniy_save_data {get; private set;}
}

class SoStore {
    ..IDに対応したScriptableObjectを管理し提供するストア..
    +List<IdSOPair> id_so_list {get; private set;}
    +Dictionary<string, ScriptableObject> id_so_pairs {get; private set;} 

    +GetSO(string id): ScriptableObject;
    +GetSO<T>(string id): T
}

struct IdSOPair {
    +string id {get; private set;}
    +ScriptableObject so {get; private set;}
}

' class GoStore {
'     ..IDに対応したGameObjectを管理して提供するストア..
'     +List<IdGoPair> id_go_list {get; private set;}
'     +Dictionary<string, GameObject> id_go_pairs {get; private set;}

'     +GetGo(string id): GameObject
'     +GetGo<T>(string id): T
' }

' struct IdMonoPair {
'     +string id {get; privaate set;}
'     +MonoBehavior mono {get; private set}
' }
' MonoStore +-- IdMonoPair

SoStore +-- IdSOPair

abstract Item {
    +int avalilable_count {get; private set;}
    +abstract Use(object targets): void

    +Item(int avalilable_count): void
}

Item +-- ItemTargetType

class WeaponTypeAffinity {
    +Dictionary<WeaponType, List<WeaponType>> strongAgainst
    +Dictionary<WeaponType, List<WeaponType>> weakAgainst
    +IsStrongAgainst(attacker: WeaponType, defender: WeaponType): bool
    +IsWeakAgainst(attacker: WeaponType, defender: WeaponType): bool
}

class WeaponStatus {
    +int[] ranges {get; private set;}
    +int power  {get; private set;}
    +WeaponType weapon_type {get; private set;}
    +WeaponCategory weapon_category {get; private set;}
}

class Weapon {
    +int available_count {get; private set;}
    +WeaponStatus weapon_status; 
    +override Use(object targets): void
    +Weapon(WeaponStatus weapon_status): void
}

enum WeaponCategory {
    PHYSICAL
    MAGICAL
}

enum WeaponType {
    SWORD
    LANCE
    AXE
    REASON
    LIGHT
    DARK
}

Weapon +-- WeaponType
Weapon +-- WeaponCategory

enum ActionType {
    ATTACK
    HEAL
    WAIT
}

enum FieldInputStateType {
    UnitSelect
    MoveSelect
    CommandSelect
}

interface IFieldInput{
    +SetProcesses(): void
    +OnNavigate(): void
    +OnDecide(): void
    +OnCancel(): void
}

class UnitSelectProcess{
    -InputActionHandler input_action_handler;
    -UnitManager unit_manager;
}

interface IUnitAction {
    ..ユニットの行動処理を規定するインターフェース..
    +ActionType action_type {get; private set;}
    +string action_name {get; protected set;}
    +CanExecute(Unit exec_unit, object target): bool
    +Execute(Unit exec_unit, object taraget): void
}

IUnitAction +-- ActionType
IUnitAction --> ActionType

class AttackAction {
}

class HealAction {
}

class WaitAction {
}

abstract Unit {
    +string unit_name {get; private set;}
    +UnitType unit_type {get; private set;}
    +Vector2Int pos {get; private set;}
    +UnitClassSO class {get; private set;}
    +bool is_alive {get; privaate set;}
    +bool is_selected {get; private set;}
    +bool has_moved {get; private set;}
    +Sprite icon {get; private set;}
    +Weapon equip_wepon {get; private set;}
    +List<Weapon> have_weapons {get; private set;}
    +List<Item> have_items {get; private set;}
    +List<IUnitAction> available_actions {get; private set;}
    +List<Tile> moveable_tiles {get; private set;}
    +List<Tile> in_range_tiles {get; private set;}

    +GridMove(Vector2 target_pos, Vector2Int target_grid_pos): void
    +virtual GetMoveableArea(Tile[,] tile_map, int map_width, int map_height): List<Vector2Int>
    +SearchMoveableArea(Tile[,] tile_map, int map_width, int map_height): void
    +SearchInRangeTiles(Tile[,] tile_map, int map_width, int map_height): void

    +Select(): void
    +DeSelect(): void
    +ResetTurnState(): void
    +TakeDamege(int amount): void
    +Heal(int amount): void
    +UpdateAvailableActions(): void
}

class AllyUnit {
    ..味方ユニットの具体的な操作・成長処理を持つクラス..
    +UnitGrowthRate growth_rate {get; private set;}
    +AllyUnitSatus unit_status {get; private set;}
    +GainExp(int exp_amount): void
    +LevelUp(): void
    +ClassPromote(): void
    +SaveData(): void;
    +LoadData(string json_text): void;
}

class EnemyUnit {
    ..敵ユニットの行動AIや移動処理を担当するクラス..
    +EnemyUnitStatus unit_status {get; private set;}
    +AIType ai_type {get; private set;}

    +override SearchMoveableArea(Tile[,] tile_map, int map_width, int map_height): void
    +MoveAgent(): void
}

struct AllyUnitSaveData {
    +string unit_id {get; privaate set;}
    +int curret_hp {get; private set;}
    +int max_hp {get; private set;}
    +int str {get; private set;}
    +int m_power {get; private set;}
    +int tec {getl private set;}
    +int agi {get; private set;}
    +int def {get; private set;}
    +int m_def {get; private set;}
    +int luck {get; private set;}
    +int physique {get; private set;}
    +int level {get; private set;}
    +int exp {get; private set;}
    +string equip_weapon_id {get; private set;}
    +List<string> have_weapon_ids {get; private set;}
    +List<string> have_item_ids {get; private set;}
}

enum AIType {
    IDLE
    REACTIVE
    AGGRESSIVE
}

EnemyUnit +-- AIType

' class UnitStatusSO {
'     ..ユニットのステータス情報を保持するScriptableObject 初期データに使用..
'     +string unit_id {get; private set;}
'     +int max_hp {get; private set;}
'     +int str {get; private set;}
'     +int m_power {get; private set;}
'     +int tec {getl private set;}
'     +int agi {get; private set;}
'     +int def {get; private set;}
'     +int m_def {get; private set;}
'     +int luck {get; private set;}
'     +int physique {get; private set;}
'     +int level {get; private set;}
' }

abstract UnitStatus {
    ..ユニットのステータス情報を保持するクラス(HPや攻撃力など)..
    +string unit_id {get; private set;}
    +int max_hp {get; private set;}
    +int current_hp {get; private set;}
    +int str {get; private set;}
    +int m_power {get; private set;}
    +int tec {getl private set;}
    +int agi {get; private set;}
    +int def {get; private set;}
    +int m_def {get; private set;}
    +int luck {get; private set;}
    +int physique {get; private set;}
    +int level {get; private set;}

    +UnitStatus(int max_hp, int current_hp, int str, int m_power, int tec, int agi, int def, int m_def, int luck, int physique): void
}

class AllyUnitSatus {
    +int exp {get; private set;}
}

class EnemyUnitStatus {
    +int base_exp_amount {get; private set;}
}

note right of UnitStatus::UnitStatus
    セーブデータからのステータス読み込みはこのコンストラクタ
end note

class UnitGrowthRate {
    +int hp_rate {get; private set;}
    +int str_rate {get; private set;}
    +int m_power_rate {get; private set;}
    +int tec_rate {get; private set;}
    +int agi_rate {get; private set;}
    +int def_rate {get; private set;}
    +int m_def_rate {get; private set;}
    +int luck_rate {get; private set;}
    +int physique_rate {get; private set;}
}

class UnitClassSO {
    +string class_name
    +int move_cost {get; private set;}
    +Sprite icon {get; private set;}
    +List<WeaponType> usable_weapon_types { get; private set; }
}

class UnitUpperClassSO {

}

class UnitLowerClassSO {
    +UnitUpperClass promotable_class {get; private set;}
}

class UnitManager {
    ..全ユニットの操作・管理を行うクラス..
    +List<AllyUnit> ally_unit {get; private set;}
    +List<EnemyUnit> enemy_unit {get; private set;}
    +Unit selected_unit {get; private set;}
    -MapManager map_manager

    +SelectUnit(Unit select_unit): void
    +DeselectUnit(): void
    +ResetAllTurnStates(): void
    +UpdateMoveableArea(Tile[,] tile_map, int map_width, int map_height): void
    +UpdateRangeTiles(Tile[,] tile_map, int map_width, int map_height): void
}

class SearchAlgorithm {
    +AStart(): void;
}

UnitManager +-- TypeUnitPair

class MapManager {
    ..マップのタイル配置や表示を管理するクラス..
    
    -MapInfo map_info
    -TileFactory tile_factory
    -CSVHandler csv_handler
    -Tile[,] map_tiles

    +ReadMapData(): int[,]
    +MapDisplay(): void
    +GetTileData(Vector2Int pos): Tile
    +UpdateMapData(Dictionary<Vector2Int, int>): void 
    +IsInBounds(Vector2Int pos): bool
    +RefreshMapDisplay(): void
    +HightRightTiles(List<Tile> tiles, Color color): void
    +ClearHightRights(): void
}

class MapSaveData {
    
}

class FactoryWithStringKey {
    -StringKeyPrefabPair[] string_key_prefab_pairs
    +Dictionary<string, GameObject> prefabs;

    +InstantiateFromStringKey(string key, Vector2 pos, Quaternion rotetion): GamaObject
    -ConvertArrayToDictionary(): void
}

struct StringKeyPrefabPair {
    +string key
    +GameObject prefab
}

class FactoryWithIntKey {
    -IntKeyPrefabPair[] int_key_prefab_pairs
    +Dictionary<Int, GameObject> prefabs;

    +InstantiateFromIntKey(int key, Vector2 pos, Quaternion rotation): GameObject
    -ConvertArrayToDictionary(): void
}

struct IntKeyPrefabPair {
    +int key
    +GameObject prefab
}

FactoryWithStringKey +-- StringKeyPrefabPair
FactoryWithIntKey +-- IntKeyPrefabPair

class MonoBehavior {

}

class ScriptableObject {

}

class CSVHandler {
    +WriteCSV(string csv_file, List<string[]> write_data): WriteResult
    +ReadCSV(string csv_file): ReadResult
}

class JsonHandler {
    +ReadJsonFromResources<T>(string file_name): List<T>
    +WriteJson<T>(T data, string file_name): void
}

class InputActionHandler {
    -PlayerInput player_input
    -Dictionary<string, Dictionary<string, System.Action<InputAction.CallbackContext>>> current_callbacks

    +SwitchActionMap(string action_map)
    +SetCallback(string action_name, System.Action<InputAction.CallbackContext> callback)
}

struct ReadResult {
    +bool is_success
    +List<string[]> read_data
    +string error_message
}

struct WriteResult {
    +bool is_success
    +string error_message
}

CSVHandler +-- ReadResult
CSVHandler +-- WriteResult

class MapInfo {
    +string csv_file_name {get; private set;}
    +int width {get; private set;}
    +int height {get; private set;}
    +Vector2Int[] initial_pos_ally {get; private set;}
    +Vector2Int[] initial_pos_enemy {get; private set;}
}

abstract Tile {
    #TileType tile_type
    +string tile_name { get; protected set; }
    +int move_cost { get; protected set; }
    +int avo_increase { get; protected set; }
    +int hp_recover { get; protected set; }

    +GetCanMove(UnitClass unit_class): bool
} 

note right of Tile::GetCanMove
    引数のユニットクラスがタイルを移動可能かを返す
end note

class Grass {

}

class Thicket {

}

class Fortress {

}

class Catsle {

}

class Sand {

}

class Forest {

}

class Water {

}

class Wall{

}

GameManager --|> MonoBehavior

UnitSelectProcess ..|> IFieldInput

AttackAction ..|> IUnitAction
HealAction ..|> IUnitAction
WaitAction ..|> IUnitAction

Item --|> ScriptableObject
Weapon --|> Item

Unit --|> MonoBehavior
Unit --> UnitClass
Unit --> Tile
Unit --> IUnitAction
Unit --> ItemInstance
Unit --> UnitStatus

AllyUnitSatus --|> UnitStatus
EnemyUnit --|> UnitStatus

UnitClass --|> ScriptableObject
UnitStatusSO --|> ScriptableObject
AllyUnit --|> Unit
AllyUnit --> UnitGrowthRate
AllyUnit --> AllyUnitSatus
EnemyUnit --|> Unit
EnemyUnit --> EnemyUnitStatus
UnitUpperClass --|> UnitClass
UnitLowerClass --|> UnitClass

TileFactory --|> BaseFactory

UnitManager --> Unit
UnitManager --> MapManager
UnitManager --> Tile
UnitManager ..|> ISavaToJson

MapManager --> CSVHandler
MapManager --> TileFactory
MapManager --> Tile

MapInfo --|> ScriptableObject

Tile --|> MonoBehavior
Grass --|> Tile
Thicket --|> Tile
Fortress --|> Tile
Catsle --|> Tile
Sand --|> Tile
Forest --|> Tile
Wall --|> Tile
Water --|> Tile


@enduml